"""
intent/train.py — Train the offline intent classifier (SVM on embeddings).

Pipeline:
    1. Load training_data.json (generated by generate_training_data.py)
    2. Embed all examples with all-MiniLM-L6-v2
    3. 80/20 stratified train/test split
    4. Train SVC(kernel='rbf', probability=True)
    5. Print accuracy + full classification report
    6. Save model to outputs/intent/intent_svm.pkl (~50KB)

Usage:
    python main.py intent-train
    (or directly: python intent/train.py)
"""

from __future__ import annotations

import json
import logging
import pickle
import sys
from pathlib import Path

import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sentence_transformers import SentenceTransformer

# Add project root to path when run directly
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import (
    INTENT_TRAINING_DATA_FILE,
    INTENT_MODEL_FILE,
    INTENT_MODEL_DIR,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
logger = logging.getLogger(__name__)


def load_training_data(path: Path) -> tuple[list[str], list[str]]:
    """Load texts and labels from training_data.json."""
    if not path.exists():
        logger.error(
            f"Training data not found at {path}. "
            "Run 'python intent/generate_training_data.py' first."
        )
        sys.exit(1)

    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    texts = [item["text"] for item in data]
    labels = [item["label"] for item in data]

    from collections import Counter
    dist = Counter(labels)
    logger.info(f"Loaded {len(texts)} examples across {len(dist)} classes:")
    for label, count in dist.most_common():
        logger.info(f"  {label:20s}: {count:3d} examples")

    return texts, labels


def embed(texts: list[str], model_name: str = "all-MiniLM-L6-v2") -> np.ndarray:
    """Embed all texts using sentence-transformers."""
    logger.info(f"Loading embedder: {model_name}")
    embedder = SentenceTransformer(model_name)
    logger.info(f"Embedding {len(texts)} examples...")
    embeddings = embedder.encode(texts, normalize_embeddings=True, show_progress_bar=True)
    logger.info(f"Embeddings shape: {embeddings.shape}")
    return embeddings


def train_svm(X_train: np.ndarray, y_train: list[str]) -> SVC:
    """Train an SVC with RBF kernel on the training embeddings."""
    logger.info("Training SVM (kernel=rbf, C=10, gamma=scale)...")
    clf = SVC(
        kernel="rbf",
        C=10.0,
        gamma="scale",
        probability=True,
        class_weight="balanced",
        random_state=42,
    )
    clf.fit(X_train, y_train)
    logger.info("Training complete.")
    return clf


def evaluate(clf: SVC, X_test: np.ndarray, y_test: list[str]) -> float:
    """Print full evaluation report. Returns test accuracy."""
    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print("\n" + "=" * 58)
    print("  INTENT CLASSIFIER — EVALUATION REPORT")
    print("=" * 58)
    print(f"  Test accuracy: {acc:.2%}  ({int(acc * len(y_test))}/{len(y_test)} correct)")
    print()
    print(classification_report(y_test, y_pred, zero_division=0))
    print("=" * 58)
    return acc


def cross_validate(clf_cls, X: np.ndarray, y: list[str], k: int = 5) -> float:
    """Run k-fold cross-validation and return mean accuracy."""
    logger.info(f"Running {k}-fold cross-validation...")
    cv = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
    clf = clf_cls(
        kernel="rbf", C=10.0, gamma="scale",
        probability=True, class_weight="balanced", random_state=42
    )
    scores = cross_val_score(clf, X, y, cv=cv, scoring="accuracy")
    logger.info(f"CV accuracy: {scores.mean():.2%} ± {scores.std():.2%}")
    return float(scores.mean())


def save_model(clf: SVC, path: Path = INTENT_MODEL_FILE):
    """Pickle the trained SVM."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(clf, f)
    size_kb = path.stat().st_size / 1024
    logger.info(f"Model saved to: {path}  ({size_kb:.1f} KB)")


def main():
    # 1. Load data
    texts, labels = load_training_data(INTENT_TRAINING_DATA_FILE)

    # 2. Embed
    X = embed(texts)

    # 3. Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, labels, test_size=0.2, stratify=labels, random_state=42
    )
    logger.info(f"Train: {len(X_train)} | Test: {len(X_test)}")

    # 4. Cross-validate
    cross_validate(SVC, X, labels)

    # 5. Train on full training split
    clf = train_svm(X_train, y_train)

    # 6. Evaluate
    evaluate(clf, X_test, y_test)

    # 7. Save
    save_model(clf)

    print("\nTo compare against TF-IDF+LogReg, run:")
    print("  python intent/compare.py")
    print("\nModel ready. Launch chatbot with:")
    print("  python main.py serve")


if __name__ == "__main__":
    main()
